---
services:
  postgres:
    image: postgres:16
    container_name: terrabase-db
    restart: always
    environment:
      POSTGRES_USER: terrabase
      POSTGRES_PASSWORD: terrabase
      POSTGRES_DB: terrabase
    ports:
      - "5432:5432"
    volumes:
      - terrabase_db_data:/var/lib/postgresql/data

  rpc:
    build:
      context: ../
      dockerfile: docker/Dockerfile.rpc
    image: terrabase-rpc
    container_name: terrabase-rpc
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://terrabase:terrabase@postgres:5432/terrabase?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - ../:/app

volumes:
  terrabase_db_data:
