api:
  dashboard: false

entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: /certs/terrabase.crt
      keyFile: /certs/terrabase.key

log:
  level: TRACE
